#ifndef SPINDULYS_FRONTEND_H
#define SPINDULYS_FRONTEND_H

#include <spindulys.h>


#if SPINDULYS_USE_NAMESPACES

#define FRONTEND_NAMESPACE_OPEN_SCOPE SPINDULYS_NAMESPACE_OPEN_SCOPE SPINDULYS_FRONTEND_NAMESPACE_OPEN_SCOPE
#define FRONTEND_NAMESPACE_CLOSE_SCOPE SPINDULYS_NAMESPACE_CLOSE_SCOPE SPINDULYS_FRONTEND_NAMESPACE_CLOSE_SCOPE

#else

#define FRONTEND_NAMESPACE_OPEN_SCOPE 
#define FRONTEND_NAMESPACE_CLOSE_SCOPE 

#endif // SPINDULYS_USE_NAMESPACE

#endif //SPINDULYS_FRONTEND_H
